# Required tools and blobs for bootmenu
bm_device = device/motorola/ruth

PRODUCT_PACKAGES += \
	bootmenu \
# config
PRODUCT_COPY_FILES += \
	${bm_device}/bootmenu/config/overclock.conf:/system/bootmenu/config/overclock.conf \
	${bm_device}/bootmenu/config/default_bootmode.conf:/system/bootmenu/config/default_bootmode.conf \
	${bm_device}/bootmenu/config/bootmenu_bypass:/system/bootmenu/config/bootmenu_bypass \
	${bm_device}/bootmenu/config/default.prop:/system/bootmenu/config/default.prop \
	${bm_device}/bootmenu/script/test.sh:/system/bootmenu/script/test.sh \
	${bm_device}/bootmenu/script/unroot.sh:/system/bootmenu/script/unroot.sh \
	${bm_device}/bootmenu/script/uninstall.sh:/system/bootmenu/script/uninstall.sh \
	${bm_device}/bootmenu/script/overclock.sh:/system/bootmenu/script/overclock.sh \
	${bm_device}/bootmenu/script/dropbear.sh:/system/bootmenu/script/dropbear.sh \
	${bm_device}/bootmenu/script/recovery_stable.sh:/system/bootmenu/script/recovery_stable.sh \
	${bm_device}/bootmenu/script/2nd-boot.sh:/system/bootmenu/script/2nd-boot.sh \
	${bm_device}/bootmenu/script/pre_bootmenu.sh:/system/bootmenu/script/pre_bootmenu.sh \
	${bm_device}/bootmenu/script/recovery.sh:/system/bootmenu/script/recovery.sh \
	${bm_device}/bootmenu/script/adbd.sh:/system/bootmenu/script/adbd.sh \
	${bm_device}/bootmenu/script/2nd-init.sh:/system/bootmenu/script/2nd-init.sh \
	${bm_device}/bootmenu/script/bootmode_clean.sh:/system/bootmenu/script/bootmode_clean.sh \
	${bm_device}/bootmenu/script/post_bootmenu.sh:/system/bootmenu/script/post_bootmenu.sh \
	${bm_device}/bootmenu/script/reboot_command.sh:/system/bootmenu/script/reboot_command.sh \
	${bm_device}/bootmenu/script/recoveryexit.sh:/system/bootmenu/script/recoveryexit.sh \
	${bm_device}/bootmenu/recovery/recovery.fstab:/system/bootmenu/recovery/recovery.fstab \
	${bm_device}/bootmenu/recovery/sbin/mke2fs:/system/bootmenu/recovery/sbin/mke2fs \
	${bm_device}/bootmenu/recovery/sbin/recovery_stable:/system/bootmenu/recovery/sbin/recovery_stable \
	${bm_device}/bootmenu/recovery/sbin/resize2fs:/system/bootmenu/recovery/sbin/resize2fs \
	${bm_device}/bootmenu/recovery/sbin/sdparted:/system/bootmenu/recovery/sbin/sdparted \
	${bm_device}/bootmenu/recovery/sbin/fix_permissions:/system/bootmenu/recovery/sbin/fix_permissions \
	${bm_device}/bootmenu/recovery/sbin/recovery:/system/bootmenu/recovery/sbin/recovery \
	${bm_device}/bootmenu/recovery/sbin/tune2fs:/system/bootmenu/recovery/sbin/tune2fs \
	${bm_device}/bootmenu/recovery/sbin/dedupe:/system/bootmenu/recovery/sbin/dedupe \
	${bm_device}/bootmenu/recovery/sbin/parted:/system/bootmenu/recovery/sbin/parted \
	${bm_device}/bootmenu/recovery/sbin/badblocks:/system/bootmenu/recovery/sbin/badblocks \
	${bm_device}/bootmenu/recovery/sbin/postrecoveryboot.sh:/system/bootmenu/recovery/sbin/postrecoveryboot.sh \
	${bm_device}/bootmenu/recovery/sbin/dump_image:/system/bootmenu/recovery/sbin/dump_image \
	${bm_device}/bootmenu/recovery/sbin/nandroid-md5.sh:/system/bootmenu/recovery/sbin/nandroid-md5.sh \
	${bm_device}/bootmenu/recovery/sbin/e2fsck:/system/bootmenu/recovery/sbin/e2fsck \
	${bm_device}/bootmenu/recovery/sbin/adbd:/system/bootmenu/recovery/sbin/adbd \
	${bm_device}/bootmenu/recovery/sbin/killrecovery.sh:/system/bootmenu/recovery/sbin/killrecovery.sh \
	${bm_device}/bootmenu/recovery/sbin/mke2fs.bin:/system/bootmenu/recovery/sbin/mke2fs.bin \
	${bm_device}/bootmenu/recovery/res/keys:/system/bootmenu/recovery/res/keys \
	${bm_device}/bootmenu/recovery/res/images/progress_bar_empty_right_round.png:/system/bootmenu/recovery/res/images/progress_bar_empty_right_round.png \
	${bm_device}/bootmenu/recovery/res/images/icon_decryption.png:/system/bootmenu/recovery/res/images/icon_decryption.png \
	${bm_device}/bootmenu/recovery/res/images/progress_bar_right_round.png:/system/bootmenu/recovery/res/images/progress_bar_right_round.png \
	${bm_device}/bootmenu/recovery/res/images/icon_clockwork.png:/system/bootmenu/recovery/res/images/icon_clockwork.png \
	${bm_device}/bootmenu/recovery/res/images/indeterminate6.png:/system/bootmenu/recovery/res/images/indeterminate6.png \
	${bm_device}/bootmenu/recovery/res/images/icon_error.png:/system/bootmenu/recovery/res/images/icon_error.png \
	${bm_device}/bootmenu/recovery/res/images/icon_installing.png:/system/bootmenu/recovery/res/images/icon_installing.png \
	${bm_device}/bootmenu/recovery/res/images/icon_done.png:/system/bootmenu/recovery/res/images/icon_done.png \
	${bm_device}/bootmenu/recovery/res/images/icon_firmware_error.png:/system/bootmenu/recovery/res/images/icon_firmware_error.png \
	${bm_device}/bootmenu/recovery/res/images/indeterminate4.png:/system/bootmenu/recovery/res/images/indeterminate4.png \
	${bm_device}/bootmenu/recovery/res/images/progress_bar_empty.png:/system/bootmenu/recovery/res/images/progress_bar_empty.png \
	${bm_device}/bootmenu/recovery/res/images/icon_encryption.png:/system/bootmenu/recovery/res/images/icon_encryption.png \
	${bm_device}/bootmenu/recovery/res/images/icon_firmware_install.png:/system/bootmenu/recovery/res/images/icon_firmware_install.png \
	${bm_device}/bootmenu/recovery/res/images/progress_fill.png:/system/bootmenu/recovery/res/images/progress_fill.png \
	${bm_device}/bootmenu/recovery/res/images/progress_bar_empty_left_round.png:/system/bootmenu/recovery/res/images/progress_bar_empty_left_round.png \
	${bm_device}/bootmenu/recovery/res/images/indeterminate5.png:/system/bootmenu/recovery/res/images/indeterminate5.png \
	${bm_device}/bootmenu/recovery/res/images/indeterminate3.png:/system/bootmenu/recovery/res/images/indeterminate3.png \
	${bm_device}/bootmenu/recovery/res/images/indeterminate1.png:/system/bootmenu/recovery/res/images/indeterminate1.png \
	${bm_device}/bootmenu/recovery/res/images/progress_bar_left_round.png:/system/bootmenu/recovery/res/images/progress_bar_left_round.png \
	${bm_device}/bootmenu/recovery/res/images/indeterminate2.png:/system/bootmenu/recovery/res/images/indeterminate2.png \
	${bm_device}/bootmenu/recovery/res/images/progress_bar_fill.png:/system/bootmenu/recovery/res/images/progress_bar_fill.png \
	${bm_device}/bootmenu/recovery/res/images/progress_empty.png:/system/bootmenu/recovery/res/images/progress_empty.png \
	${bm_device}/bootmenu/binary/lsof:/system/bootmenu/binary/lsof \
	${bm_device}/bootmenu/binary/busybox:/system/bootmenu/binary/busybox \
	${bm_device}/bootmenu/binary/hbootuser:/system/bootmenu/binary/hbootuser \
	${bm_device}/bootmenu/binary/2nd-init:/system/bootmenu/binary/2nd-init \
	${bm_device}/bootmenu/binary/logwrapper.bin:/system/bootmenu/binary/logwrapper.bin \
	${bm_device}/bootmenu/binary/adbd:/system/bootmenu/binary/adbd \
	${bm_device}/bootmenu/ext/su:/system/bootmenu/ext/su \
	${bm_device}/bootmenu/ext/Superuser.apk:/system/bootmenu/ext/Superuser.apk \
	${bm_device}/bootmenu/2nd-init/ueventd.rc:/system/bootmenu/2nd-init/ueventd.rc \
	${bm_device}/bootmenu/2nd-init/init.mapphone30_umts.rc:/system/bootmenu/2nd-init/init.mapphone30_umts.rc \
	${bm_device}/bootmenu/2nd-init/sbin/ueventd:/system/bootmenu/2nd-init/sbin/ueventd \
	${bm_device}/bootmenu/2nd-init/init.rc:/system/bootmenu/2nd-init/init.rc \
	${bm_device}/bootmenu/2nd-init/init:/system/bootmenu/2nd-init/init \
	${bm_device}/bootmenu/2nd-init/init_prep_keypad.sh:/system/bootmenu/2nd-init/init_prep_keypad.sh \
	${bm_device}/bootmenu/images/indeterminate6.png:/system/bootmenu/images/indeterminate6.png \
	${bm_device}/bootmenu/images/icon_error.png:/system/bootmenu/images/icon_error.png \
	${bm_device}/bootmenu/images/icon_installing.png:/system/bootmenu/images/icon_installing.png \
	${bm_device}/bootmenu/images/background.png:/system/bootmenu/images/background.png \
	${bm_device}/bootmenu/images/indeterminate4.png:/system/bootmenu/images/indeterminate4.png \
	${bm_device}/bootmenu/images/progress_fill.png:/system/bootmenu/images/progress_fill.png \
	${bm_device}/bootmenu/images/indeterminate5.png:/system/bootmenu/images/indeterminate5.png \
	${bm_device}/bootmenu/images/indeterminate3.png:/system/bootmenu/images/indeterminate3.png \
	${bm_device}/bootmenu/images/indeterminate1.png:/system/bootmenu/images/indeterminate1.png \
	${bm_device}/bootmenu/images/indeterminate2.png:/system/bootmenu/images/indeterminate2.png \
	${bm_device}/bootmenu/images/progress_empty.png:/system/bootmenu/images/progress_empty.png 