#!/system/bin/sh
mv /dev/nvm_proxy /dev/netmux/
mv /dev/telephony /dev/netmux/
mv /dev/sim_proxy /dev/netmux/
mv /dev/subsidy_lock /dev/netmux/
mv /dev/psd_nsapi5 /dev/netmux/
mv /dev/gps /dev/netmux/
mv /dev/opprof /dev/netmux/

mount -o remount,rw rootfs /
rm -r /sdcard
ln -s /mnt/sdcard /sdcard
mount -o remount,ro rootfs /
